name: Example workshop
type: dart # This should be either "dart" or "flutter".
steps:
  - name: Step 1
    directory: step_01
    has_solution: true
  - name: Step 2
    directory: step_02
    has_solution: false
